//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSubastaNet.SubastaServicioRemoto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubastaServicioRemoto.ISubastaServicio", CallbackContract=typeof(ClienteSubastaNet.SubastaServicioRemoto.ISubastaServicioCallback))]
    public interface ISubastaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubastaServicio/EntrarSala", ReplyAction="http://tempuri.org/ISubastaServicio/EntrarSalaResponse")]
        void EntrarSala(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubastaServicio/EntrarSala", ReplyAction="http://tempuri.org/ISubastaServicio/EntrarSalaResponse")]
        System.Threading.Tasks.Task EntrarSalaAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubastaServicio/EnviarOferta", ReplyAction="http://tempuri.org/ISubastaServicio/EnviarOfertaResponse")]
        void EnviarOferta(string nombreUsuario, double montoOferta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubastaServicio/EnviarOferta", ReplyAction="http://tempuri.org/ISubastaServicio/EnviarOfertaResponse")]
        System.Threading.Tasks.Task EnviarOfertaAsync(string nombreUsuario, double montoOferta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubastaServicioCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISubastaServicio/NotificarNuevaOfertaMax")]
        void NotificarNuevaOfertaMax(string nombreUsuario, double nuevoMonto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubastaServicio/MensajeDelSistema", ReplyAction="http://tempuri.org/ISubastaServicio/MensajeDelSistemaResponse")]
        void MensajeDelSistema(string mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubastaServicioChannel : ClienteSubastaNet.SubastaServicioRemoto.ISubastaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubastaServicioClient : System.ServiceModel.DuplexClientBase<ClienteSubastaNet.SubastaServicioRemoto.ISubastaServicio>, ClienteSubastaNet.SubastaServicioRemoto.ISubastaServicio {
        
        public SubastaServicioClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SubastaServicioClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SubastaServicioClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SubastaServicioClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SubastaServicioClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void EntrarSala(string nombreUsuario) {
            base.Channel.EntrarSala(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task EntrarSalaAsync(string nombreUsuario) {
            return base.Channel.EntrarSalaAsync(nombreUsuario);
        }
        
        public void EnviarOferta(string nombreUsuario, double montoOferta) {
            base.Channel.EnviarOferta(nombreUsuario, montoOferta);
        }
        
        public System.Threading.Tasks.Task EnviarOfertaAsync(string nombreUsuario, double montoOferta) {
            return base.Channel.EnviarOfertaAsync(nombreUsuario, montoOferta);
        }
    }
}
