//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSubastaNet.InicioSesionServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InicioSesionServicio.IInicioSesionServicio")]
    public interface IInicioSesionServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInicioSesionServicio/IniciarSesion", ReplyAction="http://tempuri.org/IInicioSesionServicio/IniciarSesionResponse")]
        bool IniciarSesion(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInicioSesionServicio/IniciarSesion", ReplyAction="http://tempuri.org/IInicioSesionServicio/IniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInicioSesionServicio/VerificarNombre", ReplyAction="http://tempuri.org/IInicioSesionServicio/VerificarNombreResponse")]
        bool VerificarNombre(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInicioSesionServicio/VerificarNombre", ReplyAction="http://tempuri.org/IInicioSesionServicio/VerificarNombreResponse")]
        System.Threading.Tasks.Task<bool> VerificarNombreAsync(string nombreUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInicioSesionServicioChannel : ClienteSubastaNet.InicioSesionServicio.IInicioSesionServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InicioSesionServicioClient : System.ServiceModel.ClientBase<ClienteSubastaNet.InicioSesionServicio.IInicioSesionServicio>, ClienteSubastaNet.InicioSesionServicio.IInicioSesionServicio {
        
        public InicioSesionServicioClient() {
        }
        
        public InicioSesionServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InicioSesionServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InicioSesionServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InicioSesionServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IniciarSesion(string nombreUsuario) {
            return base.Channel.IniciarSesion(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(string nombreUsuario) {
            return base.Channel.IniciarSesionAsync(nombreUsuario);
        }
        
        public bool VerificarNombre(string nombreUsuario) {
            return base.Channel.VerificarNombre(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarNombreAsync(string nombreUsuario) {
            return base.Channel.VerificarNombreAsync(nombreUsuario);
        }
    }
}
